---
title: "COAST Research Proposal"
author: "Desiree Zhuk"
format: html
editor: visual
---

## Project Description (65 points)

(1500 words)

Clear description of the project, its goals and significance (30 points)

Statements sufficiently referenced (5 points)

Use of original, peer-reviewed literature, both foundational and current (5 points)

Clearly stated hypotheses or objectives (5 points)

Experimental design and methodology (15 points)

## Timeline (10 points)

(250 words)

Clear plan for use of award beginning May 15, 2023

Can reference activities prior to 5/15/2023 but funds cannot be used for anything before that date

Interim milestone dates

Anticipated graduation date

## Need of Research (7 points)

(250 words)

Clearly articulate the scientific need for your research

How will your work contribute to the advancement of your field?

What intellectual contribution will your expected results make?

## Relevance to California (3 points)

(100 words)

Work supported NOT limited to CA

Priority to projects applicable to CA needs

Describe how research is relevant to CA

## Budget and Justification (15 points)

(250 words)

Construct your own!

You need a Departmental Commitment Form

Living expenses Financial aid office: Unqualified scholarship, Taxable, Financial aid impact

Requests for personal living expenses and/or tuition are
equal in merit to requests for research-related expenses.

Explain HOW the award will help you in detail: Rent, Monthly living expenses, Child care

What will this award allow you to do that wouldn't otherwise be possible? E.g., reduce your hours at an unrelated job and therefore make progress toward your degree more quickly
