---
title: "Southern Sea Otter Nutrient Accesibility in Low Risk Areas within San Francisco Bay"
author: "Desiree Zhuk 8/21/23"
format: docx
editor: visual
bibliography: references.bib
---

[Desiree's GitHub Repository](https://github.com/DesireeZhuk/BIOL708)

## Introduction

The historical challenges faced by southern sea otters, including habitat loss and degradation due to human activities, have raised concerns about their population stagnation and limited genetic diversity in concentrated areas. The reintroduction of southern sea otters to San Francisco Bay presents an opportunity to restore their presence in an ecosystem impacted by invasive species. This endeavor holds potential to conserve vital marsh and eelgrass habitats, support population dispersal, and promote ecotourism. However, before we can propose to introduce sea otters, we must ensure that they can prosper within the Bay. Previous research has highlighted low-risk areas, based on the spatial distribution of vessel traffic, environmental contaminants, major oil spills and commercial fishing [@rudebusch2020]. Hughes et al. mapped highly suitable habitat types and projected density of sea otters in the Bay [@hughes2019]. With an overlap of zones of high possible density of sea otters and areas of low anthropogenic risk, we can pinpoint possible areas for successful re-colonization in the Bay, depending on the ability of the animals to forage adequately. The project seeks to assess the potential for successful foraging within the Bay's different regions, considering both nutrition availability and protection from anthropogenic threats. By addressing key questions about habitat quality, foraging possibilities, and their impact on otter abundance, the research will provide mechanistic models of seagrass and mudflat habitats. These models will showcase invertebrate prey productivity relative to sea otter habitat use, guiding conservation efforts.
